# Generated by Django 2.2.5 on 2020-05-16 12:43

import career_center.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=career_center.models.upload_institution_image),
        ),
    ]
