# Generated by Django 2.2.5 on 2020-05-16 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('career_center', '0001_initial'),
        ('common', '0001_initial'),
        ('user', '0003_remove_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=user.models.upload_avatar),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('citizenship', models.CharField(max_length=255)),
                ('desired_position', models.CharField(max_length=255)),
                ('working_experience', models.CharField(max_length=2000)),
                ('education_degree', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=2000)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to=user.models.upload_resume)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.City')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career_center.Institution')),
                ('main_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Industry')),
            ],
        ),
    ]
