# Generated by Django 2.2.5 on 2020-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200516_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='role', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
