# Generated by Django 2.2.5 on 2020-05-16 14:01

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200516_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
